### ISSUE TITLE
Link to migration guide for v0.4.0.0

### ISSUE THREAD

**Issue by vrom911** [vaclavsvejcar/headroom#65]
I have installed the tool from sources and I am on the currently unreleased version `0.4.0.0`.

I received an extremely useful hint when I bumped into the issue in my config:
```shell
$ headroom run
headroom, v0.4.0.0 :: https://github.com/vaclavsvejcar/headroom
ERROR: Cannot find 'version' key in your YAML configuration file (.headroom.yaml), which is required to check compatibility of configuration file. This functionality has been added in version 'v0.4.0.0', please check following migration guide for more details:
	- http://doc.norcane.com/headroom/v0.4.0.0/migration-guide
```

However, the link doesn't work for me now (I assume it is because I am at the newest unreleased version.
Could you please help me to find the migration guide which I could use at the moment? (I am probably missing some docs in the repo, sorry for that)

**Comment by vaclavsvejcar** [comment]
Hello Veronika,

yes the cause is that because `v0.4.0.0` is not released yet, I haven't uploaded the documentation for this version. Headroom's microsite documentation is stored in `/doc/microsite` directory and it uses [mkdocs](https://www.mkdocs.org), so if you install this tool, you can then easily run it locally for selected version by running `mkdocs serve` in that directory and opening http://127.0.0.1:8000 in browser. Or, if you're ok with reading just the _Markdown_ source, you can find this migration guide in [/doc/microsite/docs/migration-guide.md](https://github.com/vaclavsvejcar/headroom/blob/master/doc/microsite/docs/migration-guide.md)

Let me know if that helps 🙂

**Comment by vrom911** [comment]
That's exactly what I need! Thanks so much 👍🏼

**Comment by vaclavsvejcar** [comment]
Anyway I should add this info how to run documentation locally to _README_, so I'm reopening this ticket for this purpose.
