### ISSUE TITLE
False-positive detection of module

### ISSUE THREAD

**Issue by vrom911** [vaclavsvejcar/headroom#67]
It seems to take the first line containing `module` word at the start as the indicator of the module. Like in this example:

```haskell
{- |
Module                  : contains
Copyright               : (c) 2021 Kowainik
SPDX-License-Identifier : MPL-2.0
Maintainer              : Kowainik <xrom.xkov@gmail.com>
Stability               : Stable
Portability             : Portable

!!! INSERT MODULE LONG DESCRIPTION !!!
-}

{- |
Copyright: (c) 2018-2020 Kowainik
SPDX-License-Identifier: MPL-2.0
Maintainer: Kowainik <xrom.xkov@gmail.com>

Implementation of /Tagged Partial Bidirectional Isomorphism/. This
module contains the 'BiMap' type that represents conversion between
two types with the possibility of failure.

See "Toml.Codec.BiMap.Conversion" for examples of 'BiMap' with
specific types. The 'BiMap' concept is general and is not specific to
TOML, but in this package most usages of 'BiMap' are between TOML
values and Haskell values.
-}

module Toml.Codec.BiMap
```

It took the line "module contains the 'BiMap' type that represents conversion between" as the module name and didn't modified the header, but added a new one instead.

**Comment by vaclavsvejcar** [comment]
Hi, thanks for reporting this! Unfortunately it seems to be the same problem as #57. In current implementation, when Headroom searches for `putAfter`/`putBefore` rules, in naively compares the pattern to every line, without considering whether the possible match is not inside comment (in that case it shouldn't be matched, exactly like in your example). I was hoping this is kinda not frequent issue so I can work on that later (because it requires a lot of internal changes and rewrites), but as you confirmed, this should be addressed as soon as possible.

Unfortunately AFAIK there's no workaround for this at this moment, except for defining some crazy style regular pattern in `putBefore`/`putAfter`. I'll try to fix this one as soon as possible and include it back to the [v0.4.0.0](https://github.com/vaclavsvejcar/headroom/milestone/10) release.

**Comment by vaclavsvejcar** [comment]
@vrom911 Hello, during last two weeks I rewrote the code responsible for finding and processing headers, so it should be now more robust and issues like this one or #57 should not happen anymore. I tested it on some of my projects, if you have some time, can you also please retest the laster version of Headroom from `master` and see if it fixes this issue for you? Thanks a lot in advance 🙂

**Comment by vrom911** [comment]
Hey @vaclavsvejcar , sorry for the delay. I have tested on my use case, and `headroom` works perfectly now! Thank you so much for your hard work 🤗

**Comment by vaclavsvejcar** [comment]
Hi @vrom911, thanks for your feedback, I'm happy that it helped 🙂 This was the last thing I wanted to verify before releasing [v0.4.0.0](https://github.com/vaclavsvejcar/headroom/milestone/10), so you can expect this final release soon 🙂
